### ISSUE TITLE
How can I get uncertainty quantification metrics result?

### ISSUE THREAD

**Issue by zhenshuozhang** [Yinghao-Li/MUBen#1]
I change "uncertainty_method": "TemperatureScaling" in config file and use the command 'PYTHONPATH="." python ./run/grover.py ./scripts/config_grover.json'. But the output is only roc-auc. How can I get the UQ value such as ECE, NLL and BS?

**Comment by Yinghao-Li** [comment]
Hi,

Thanks for bringing this to our attention. Currently, you need to save the predicted results first (in your circumstance, at `./<result_folder>/<dataset_name>/GROVER/TemperatureScaling/<seed>/preds/0.pt` by default). Then you can use the [results_get_metrics.py](https://github.com/Yinghao-Li/UncertaintyBenchmark/blob/main/assist/results_get_metrics.py) to calculate all metrics. The output will be stored in the `./<result_folder>/RESULTS/GROVER-<dataset_name>.csv` file. Notice that this file already exists in the repo if you use the default `--result_folder=output` and you need to check whether it is updated to reveal your experiment results.

We apologize for not mentioning this in README. We'll update the description shortly.

**Comment by zhenshuozhang** [comment]
> 

Thank you for your response. I have a question related to uncertainty estimation, which may not be entirely a code-related issue. It seems that uncertainty metrics only require the model's predictions and labels, without utilizing the uncertainty provided by uncertainty models (such as variance). And a single deterministic model can also provide predictions. So, I would like to know where the role of uncertainty estimation models lies. For example, does it aim to reduce the result value of uncertainty quantification metrics?

**Comment by Yinghao-Li** [comment]
Hi,

For classification, the Sigmoid/Softmax output intrinsically carries the uncertainty information. For regression, we do use the predicted variance for NLL and CE calculation. RMSE and MAE are not uncertainty metrics and thus do not require variances; NLL includes Gaussian likelihood and thus requires the variance, CE compares the empirical and theoretical confidence intervals, which are calculated using the Gaussian CDF. You can find more information in [our paper](https://arxiv.org/abs/2306.10060) and [(Kuleshov et al. 2018)](https://arxiv.org/abs/1807.00263).

**Comment by zhenshuozhang** [comment]
Thanks for your answer!

**Comment by Yinghao-Li** [comment]
You're welcome. Feel free to let us know if you encounter any other issues!
