### ISSUE TITLE
Why can Focal Loss and Temprature Scaling be seen as an uncertainty method?

### ISSUE THREAD

**Issue by zhenshuozhang** [Yinghao-Li/MUBen#2]
It seems that they are also kinds of single deterministic models because they neither sample nor provide variance.

**Comment by Yinghao-Li** [comment]
These methods are developed to improve the [model calibration](tidyverse.org/blog/2022/11/model-calibration/#:~:text=The%20goal%20of%20model%20calibration,them%20to%20have%20better%20properties.) to better align the output probabilities (confidence to prediction) with prediction accuracy. Notice that methods are only compatible with classification tasks whose output is already probability scores (in other words, model confidence) to each class, and no additional variance is required to estimate uncertainty.

**Comment by zhenshuozhang** [comment]
> 

Thanks for your kind reply! And I have another question that is, what is the function of 'inverse_standardize_preds' defined in trainer.py? The reason for using it might not be mentioned in your paper.

**Comment by Yinghao-Li** [comment]
It is common practice for regression tasks in the material science domain to standardize the training labels before using them to supervise the model training. Therefore we need to reverse the process for the model-predicted values to get the actual results. For your reference, the standardization happens [here](https://github.com/Yinghao-Li/UncertaintyBenchmark/blob/048b02e8483182efa80018ea81c73cf6b5f51a46/muben/base/train/trainer.py#L109C22-L109C22).

**Comment by zhenshuozhang** [comment]
> It is common practice for regression tasks in the material science domain to standardize the training labels before using them to supervise the model training. Therefore we need to reverse the process for the model-predicted values to get the actual results. For your reference, the standardization happens [here](https://github.com/Yinghao-Li/UncertaintyBenchmark/blob/048b02e8483182efa80018ea81c73cf6b5f51a46/muben/base/train/trainer.py#L109C22-L109C22).

Your explanation is very clear, thank you for your reply!

**Comment by Yinghao-Li** [comment]
You're welcome!
