### ISSUE TITLE
A question about the definition of Expected Calibration Error in Appendix D.2

### ISSUE THREAD

**Issue by zhenshuozhang** [Yinghao-Li/MUBen#3]
I think the definition of 'conf' only considers the confidence of a positive case. 

Consider a sample with a true label of 0 and a predicted probability of 0.1. This should represent the model's confidence in class 0, rather than a lack of confidence in class 1. According to the formula in your paper, the calibration error for this sample would be CE = acc - conf = 1 - 0.1 = 0.9. However, if I swap class labels 0 and 1, making the true label 1 and the predicted probability 0.9, the calibration error becomes CE = acc - conf = 1 - 0.9 = 0.1. This is contradictory.

However, the 'binary_calibration_error function' in the 'torchmetrics.functional.classification' library in the code addresses this issue, ensuring that swapping sample labels does not affect the output results. Therefore, the code should be correct.

**Comment by Yinghao-Li** [comment]
Hi,

That's a good point. Upon double-checking, the description on page 3 is correct, as it targets the multi-class case. But we did make a mistake in Equation 17. We'll correct this in a future version of the paper.

**Comment by Yinghao-Li** [comment]
Hi,

That's a good point. For binary classification, the calibration error calculation is not symmetric for classes 0 and 1. You can refer to [this tutorial](https://towardsdatascience.com/expected-calibration-error-ece-a-step-by-step-visual-explanation-with-python-code-c3e9aa12937d) for details.

**Comment by zhenshuozhang** [comment]
> Hi,
> 
> That's a good point. For binary classification, the calibration error calculation is not symmetric for classes 0 and 1. You can refer to [this tutorial](https://towardsdatascience.com/expected-calibration-error-ece-a-step-by-step-visual-explanation-with-python-code-c3e9aa12937d) for details.

Based on my testing, the results obtained from the 'binary_calibration_error' function in the 'torchmetrics.functional.classification' library are symmetric for classes 0 and 1, whereas the results from the code proposed in that tutorial are asymmetric. And someone in the comments of that tutorial pointed out the same issue.

As for the experimental details, the test data I used was
1. pred_1=[0.1, 0.2, 0.8], label_1=[0, 0, 1]
2. pred_2=1-pred_1=[0.9, 0.8, 0.2], label_2=1-label_1=[1, 1, 0]
The results given by 'binary_calibration_error' are 0.166 and 0.166. And the results given by that tutorial are 0.633 and 0.366.
I guess that in the 'binary_calibration_error' function, all confidences are mapped to the interval [0.5, 1]. For example, when pred = 0.1, the confidence would be 1 - 0.1 = 0.9.

**Comment by Yinghao-Li** [comment]
After reviewing the implementations, you're correct. Equation 17 does not align with the code implementation. The accuracy calculation can be corrected as:

$$\text{acc}=\frac{1}{|B_s|}\sum_{n\in B_s} y_n$$

I apologize for the oversight and resulting confusion. I appreciate your attention to detail in bringing this to light.

**Comment by zhenshuozhang** [comment]
> After reviewing the implementations, you're correct. Equation 17 does not align with the code implementation. The accuracy calculation can be corrected as:
> 
> acc=1|Bs|∑n∈Bsyn
> 
> I apologize for the oversight and resulting confusion. I appreciate your attention to detail in bringing this to light.

Thanks for your update
